name = "edge"
background = "light"

[colors]
black  = "#dde2e7"
bg_dim = "#e8ebf0"

bg0 = "#fafafa"
bg1 = "#eef1f4"
bg2 = "#e8ebf0"
bg3 = "#e8ebf0"
bg4 = "#dde2e7"

grey     = "#8790a0"
grey_dim = "#bac3cb"

fg0 = "#4b505b"
fg1 = "darken(fg0, 0.05)"

red    = "#d05858"
green  = "#608e32"
yellow = "#be7e05"
blue   = "#5079be"
purple = "#b05ccc"
cyan   = "#3a8b84"

filled_red    = "#e17373"
filled_green  = "#76af6f"
filled_blue   = "#6996e0"
filled_purple = "#bf75d6"

bg_red    = "#f6e4e4"
bg_green  = "#e5eee4"
bg_yellow = "#f0ece2"
bg_blue   = "#e3eaf6"
bg_purple = "#f4e9f8"
bg_grey   = "#bcc5cf"

[highlights]
Normal      = "fg0 bg0"
NormalNC    = "fg0 bg0"
NormalFloat = "fg0 bg3"

EndOfBuffer = "bg4"
NonText     = "bg4"
Whitespace  = "bg4"

Cursor        = "bg0 fg0"
Cursorline   = "- bg1"
CursorlineNr = "fg0 bg1"
ColorColumn  = "- bg2"
Folded       = "fg0 bg1"
LineNr       = "grey_dim"
SignColumn   = "link:LineNr"
Visual       = "- bg3"
WinSeparator = "bg4"

Pmenu      = "fg0 bg3"
PmenuSbar  = "- bg3"
PmenuSel   = "bg0 filled_blue"
PmenuThumb = "- bg_grey"

StatusLine    = "fg0 bg1"
StatusLineNC  = "grey_dim bg1"
TabLine       = "fg0 bg4"
TabLineFill   = "fg0 bg1"
TabLineSel = "bg0 filled_blue"

Search     = "bg0 yellow"
CurSearch  = "bg0 red"
IncSearch  = "- - r"
Substitute = "bg0 red"
MatchParen = "- bg3"

Added   = "green"
Changed = "blue"
Removed = "red"

DiffAdd    = "green bg_green"
DiffText   = "blue bg_blue"
DiffDelete = "red bg_red"

ErrorMsg   = "red"
ModeMsg    = "grey"
MoreMsg    = "cyan"
Question   = "blue"
QuickFixLine = "- bg3 b"
WarningMsg = "yellow"

SpellBad   = "- - c red"
SpellCap   = "- - c yellow"
SpellLocal = "- - c blue"
SpellRare  = "- - c cyan"

# Diagnostics
DiagnosticUnderlineOk    = "- - u green"
DiagnosticUnderlineInfo  = "- - u blue"
DiagnosticUnderlineHint  = "- - u grey"
DiagnosticUnderlineWarn  = "- - u yellow"
DiagnosticUnderlineError = "- - u red"

DiagnosticOk    = "green bg_green"
DiagnosticInfo  = "blue bg_blue"
DiagnosticHint  = "grey bg2"
DiagnosticWarn  = "yellow bg_yellow"
DiagnosticError = "red bg_red"

DiagnosticSignOk    = "green"
DiagnosticSignInfo  = "blue"
DiagnosticSignHint  = "grey"
DiagnosticSignWarn  = "yellow"
DiagnosticSignError = "red"

# Syntax
Bold         = "fg0 - b"
Character    = "green"
Comment      = "grey"
Constant     = "yellow"
Debug        = "red"
Delimiter    = "grey"
Directory    = "blue"
Error        = "red"
Function     = "blue"
Identifier   = "fg0"
Include      = "blue"
Italic       = "fg0 - i"
Keyword      = "purple"
Operator     = "purple"
PreProc      = "cyan"
Special      = "cyan"
Statement    = "purple"
StorageClass = "purple"
String       = "green"
Structure    = "purple"
Title        = "red"
Todo         = "bg0 yellow"
Type         = "cyan"
Underlined   = "fg0 - u"

# treesitter
"@attribute"             = "link:PreProc"
"@boolean"               = "link:Constant"
"@character"             = "link:String"
"@character.special"     = "link:Constant"
"@comment"               = "link:Comment"
"@comment.todo.comment"  = "link:Todo"
"@conceal"               = "link:Comment"
"@conditional"           = "link:Statement"
"@constant"              = "link:Constant"
"@constant.builtin"      = "link:Statement"
"@constant.macro"        = "link:Special"
"@constructor"           = "blue"
"@error"                 = "link:Error"
"@exception"             = "link:Keyword"
"@field"                 = "link:Identifier"
"@float"                 = "link:Constant"
"@function"              = "link:Function"
"@function.builtin"      = "link:Function"
"@function.macro"        = "link:PreProc"
"@include"               = "link:Include"
"@keyword"               = "link:Keyword"
"@keyword.coroutine"     = "link:Keyword"
"@keyword.directive"     = "link:PreProc"
"@keyword.function"      = "link:Keyword"
"@keyword.import"        = "link:Include"
"@keyword.operator"      = "link:Operator"
"@label"                 = "link:Special"
"@method"                = "link:Function"
"@module"                = "link:Type"
"@namespace"             = "link:Statement"
"@number"                = "link:Constant"
"@operator"              = "link:Operator"
"@parameter"             = "link:Identifier"
"@preproc"               = "link:PreProc"
"@property"              = "link:Identifier"
"@punctuation.bracket"   = "link:Delimiter"
"@punctuation.delimiter" = "link:Delimiter"
"@punctuation.special"   = "yellow"
"@repeat"                = "link:Statement"
"@string.escape"         = "link:Special"
"@string"                = "link:String"
"@string.regexp"         = "yellow"
"@string.special"        = "link:Special"
"@tag"                   = "blue"
"@tag.attribute"         = "fg0"
"@tag.delimiter"         = "blue"
"@text"                  = "fg0"
"@text.title"            = "link:Title"
"@text.uri"              = "link:Uri"
"@text.warning"          = "link:Todo"
"@type.builtin"          = "link:Statement"
"@type.definition"       = "link:Keyword"
"@type"                  = "link:Type"
"@type.qualifier"        = "link:Keyword"
"@variable"              = "link:Identifier"
"@variable.builtin"      = "link:Statement"
"@variable.member"       = "link:Identifier"
"@variable.parameter"    = "link:Identifier"

# Language specific highlights
"@constant.bash"                 = "fg0"
"@constructor.lua"               = "link:Delimiter"
"@keyword.directive.bash"        = "link:Comment"
"@keyword.directive.python"      = "link:Comment"
"@keyword.exception.rust"        = "link:PreProc"
"@property.json"                 = "blue"
"@property.toml"                 = "blue"
"@property.yaml"                 = "blue"
"@string.csv"                    = "fg0"
"@string.special.path.nix"       = "cyan"
"@variable.parameter.bash"       = "fg0"
"@variable.parameter.powershell" = "fg0"

# Markup highlights
"@markup.heading.1"  = "red"
"@markup.heading.2"  = "yellow"
"@markup.heading.3"  = "green"
"@markup.heading.4"  = "cyan"
"@markup.heading.5"  = "blue"
"@markup.heading.6"  = "purple"
"@markup.list"       = "green"
"@markup.link.label" = "blue - u"
"@markup.link.url"   = "cyan - u"
"@markup.raw"        = "link:ColorColumn"
"@markup.raw.block"  = "link:ColorColumn"

"@punctuation.special.markdown" = "link:Comment"

# Non treesitter highlights
csvCol0 = "fg0"
csvCol1 = "blue"
csvCol2 = "yellow"
csvCol3 = "cyan"
csvCol4 = "green"
csvCol5 = "purple"
csvCol6 = "red"
csvCol7 = "cyan"
csvCol8 = "grey"

# Plugins
BlinkCmpMenu              = "fg0 bg3"
BlinkCmpKind              = "link:Special"
BlinkCmpKindClass         = "link:Type"
BlinkCmpKindColor         = "link:Special"
BlinkCmpKindConstant      = "link:Constant"
BlinkCmpKindConstructor   = "link:@constructor"
BlinkCmpKindEnum          = "link:Constant"
BlinkCmpKindEnumMember    = "link:@property"
BlinkCmpKindEvent         = "link:Special"
BlinkCmpKindField         = "fg0"
BlinkCmpKindFile          = "fg0"
BlinkCmpKindFolder        = "link:Directory"
BlinkCmpKindFunction      = "link:Function"
BlinkCmpKindInterface     = "link:Type"
BlinkCmpKindKeyword       = "link:Keyword"
BlinkCmpKindMethod        = "link:Function"
BlinkCmpKindModule        = "link:Type"
BlinkCmpKindOperator      = "link:Operator"
BlinkCmpKindProperty      = "link:@property"
BlinkCmpKindReference     = "fg0"
BlinkCmpKindSnippet       = "link:String"
BlinkCmpKindStruct        = "link:Type"
BlinkCmpKindText          = "link:String"
BlinkCmpKindTypeParameter = "link:Identifier"
BlinkCmpKindUnit          = "link:Constant"
BlinkCmpKindValue         = "fg0"
BlinkCmpKindVariable      = "fg0"
BlinkCmpDoc               = "fg0 bg3"
BlinkCmpDocBorder         = "bg3 bg3"
BlinkCmpDocSeparator      = "fg0 bg3"
BlinkCmpLabelDeprecated   = "link:Comment"

NvimTreeFolderIcon   = "link:Directory"
NvimTreeIndentMarker = "link:Directory"
NvimTreeWindowPicker = "bg0 filled_blue b"
NvimTreeRootFolder   = "purple"
NvimTreeSpecialFile  = "yellow"
NvimTreeExecFile     = "green"
NvimTreeDeletedIcon  = "red"
NvimTreeGitMergeIcon = "yellow"
NvimTreeGitDirtyIcon = "red"

FzfLuaBorder     = "link:Comment"
FzfLuaBufNr      = "green"
FzfLuaHeaderBind = "link:Special"
FzfLuaHeaderText = "link:Title"
FzfLuaLivePrompt  = "fg0"
FzfLuaPathLineNr = "fg0"
FzfLuaTabMarker  = "green"
FzfLuaTabTitle   = "link:Title"
FzfLuaTitle      = "fg0"

IblIndent     = "link:NonText"
IblScope      = "link:LineNr"
IblWhitespace = "link:Whitespace"

AgenticTitle             = "bg0 filled_blue b"
AgenticDiffAddWord       = "bg0 filled_green b"
AgenticDiffDeleteWord    = "bg0 filled_red b"
AgenticSpinnerGenerating = "cyan - b"
AgenticSpinnerSearching  = "yellow - b"
AgenticSpinnerThinking   = "purple - b"
AgenticStatusCompleted   = "green"
AgenticStatusPending     = "purple"
AgenticStatusFailed      = "red"

WhichKeyNormal = "fg0 bg1"

[globals]
terminal_color_0          = "black"
terminal_color_1          = "red"
terminal_color_2          = "green"
terminal_color_3          = "yellow"
terminal_color_4          = "blue"
terminal_color_5          = "purple"
terminal_color_6          = "cyan"
terminal_color_7          = "fg0"
terminal_color_8          = "grey"
terminal_color_9          = "red"
terminal_color_10         = "green"
terminal_color_11         = "yellow"
terminal_color_12         = "blue"
terminal_color_13         = "purple"
terminal_color_14         = "cyan"
terminal_color_15         = "fg1"
terminal_color_background = "bg0"
terminal_color_foreground = "fg0"
