name = "edge-dev"
background = "light"

[hues]

base   = 225
red    = 350
orange = 25
yellow = 40
green  = 90
cyan   = 195
sky    = 205
blue   = 220
purple = 265

[colors]

bg0 = "hsl($base, 0.2, 0.98)" # Main background
bg1 = "hsl($base, 0.2, 0.95)" # Cursorline
bg2 = "hsl($base, 0.2, 0.92)" # Statusline/Code snippet bg
bg3 = "hsl($base, 0.2, 0.88)" # Non text/Pmenu background
bg4 = "hsl($base, 0.2, 0.80)" # LineNr

grey = "hsl($base, 0.15, 0.50)"

fg0 = "hsl($base, 0.15, 0.40)"
fg1 = "hsl($base, 0.15, 0.30)"
fg2 = "hsl($base, 0.15, 0.22)"

red    = "hsl($red, 0.55, 0.45)"
orange = "hsl($orange, 1, 0.30)"    # Check
yellow = "hsl($yellow, 1, 0.32)"    # Check
green  = "hsl($green, 0.75, 0.25)"  # Check
cyan   = "hsl($cyan, 0.75, 0.30)"
sky    = "hsl($sky, 0.75, 0.28)"
blue   = "hsl($blue, 0.55, 0.45)"   # Check
purple = "hsl($purple, 0.45, 0.50)"

filled_red    = "lighten(red, 0.1)"
filled_green  = "lighten(green, 0.1)"
filled_blue   = "lighten(blue, 0.1)"
filled_purple = "lighten(purple, 0.1)"

bg_red    = "mix(red, bg0, 0.1)"
bg_green  = "mix(green, bg0, 0.1)"
bg_yellow = "mix(yellow, bg0, 0.1)"
bg_blue   = "mix(blue, bg0, 0.1)"

visual_bg = "mix(blue, bg0, 0.15)"

diff_add_bg    = "mix(green, bg0, 0.2)"
diff_text_bg   = "mix(cyan, bg0, 0.2)"
diff_delete_bg = "mix(red, bg0, 0.2)"

black = "bg2"
statusline_bg = "bg2"

[highlights]

Normal      = "fg1 bg0"
NormalNC    = "fg1 bg0"
NormalFloat = "fg1 bg3"

EndOfBuffer = "bg3"
NonText     = "bg3"
Whitespace  = "bg3"

Cursor        = "bg0 fg1"
Cursorline   = "- bg1"
CursorlineNr = "fg1 bg1 b"
ColorColumn  = "- bg2"
Folded       = "fg1 bg1"
LineNr       = "bg4"
SignColumn   = "link:LineNr"
Visual       = "- visual_bg"
WinSeparator = "bg3"

Pmenu      = "fg1 bg3"
PmenuSbar  = "- bg3"
PmenuSel   = "bg0 filled_blue"
PmenuThumb = "- grey"

StatusLine    = "fg1 statusline_bg"
StatusLineNC  = "fg0 statusline_bg"
TabLine       = "fg1 bg4"
TabLineFill   = "fg1 statusline_bg"
TabLineSel    = "bg0 filled_blue"

Search     = "bg0 yellow"
CurSearch  = "bg0 orange"
IncSearch  = "- - r"
Substitute = "bg0 orange"
MatchParen = "- bg3"

Added   = "filled_green"
Changed = "filled_blue"
Removed = "filled_red"

DiffAdd    = "green diff_add_bg"
DiffText   = "blue diff_text_bg"
DiffDelete = "red diff_delete_bg"

ErrorMsg   = "red"
ModeMsg    = "grey"
MoreMsg    = "cyan"
Question   = "blue"
QuickFixLine = "- bg3 b"
WarningMsg = "yellow"

SpellBad   = "- - c red"
SpellCap   = "- - c yellow"
SpellLocal = "- - c blue"
SpellRare  = "- - c cyan"

# Diagnostics
DiagnosticUnderlineOk    = "- - u green"
DiagnosticUnderlineInfo  = "- - u blue"
DiagnosticUnderlineHint  = "- - u grey"
DiagnosticUnderlineWarn  = "- - u yellow"
DiagnosticUnderlineError = "- - u red"

DiagnosticOk    = "green bg_green"
DiagnosticInfo  = "blue bg_blue"
DiagnosticHint  = "grey bg2"
DiagnosticWarn  = "yellow bg_yellow"
DiagnosticError = "red bg_red"

DiagnosticSignOk    = "green"
DiagnosticSignInfo  = "blue"
DiagnosticSignHint  = "grey"
DiagnosticSignWarn  = "yellow"
DiagnosticSignError = "red"

# Syntax
Bold         = "fg1 - b"
Character    = "green"
Comment      = "grey"
Constant     = "orange"
Debug        = "red"
Delimiter    = "fg0"
Directory    = "blue"
Error        = "red"
Function     = "blue"
Identifier   = "fg1"
Include      = "blue"
Italic       = "fg1 - i"
Keyword      = "purple"
Operator     = "sky"
PreProc      = "cyan"
Special      = "sky"
Statement    = "purple"
StorageClass = "purple"
String       = "green"
Structure    = "purple"
Title        = "red"
Todo         = "bg0 yellow"
Type         = "cyan"
Underlined   = "fg1 - u"

# treesitter
"@attribute"             = "link:PreProc"
"@boolean"               = "link:Constant"
"@character"             = "link:String"
"@character.special"     = "link:Constant"
"@comment"               = "link:Comment"
"@comment.todo.comment"  = "link:Todo"
"@conceal"               = "link:Comment"
"@conditional"           = "link:Statement"
"@constant"              = "link:Constant"
"@constant.builtin"      = "link:Statement"
"@constant.macro"        = "link:Special"
"@constructor"           = "blue"
"@error"                 = "link:Error"
"@exception"             = "link:Keyword"
"@field"                 = "link:Identifier"
"@float"                 = "link:Constant"
"@function"              = "link:Function"
"@function.builtin"      = "link:Function"
"@function.macro"        = "link:PreProc"
"@include"               = "link:Include"
"@keyword"               = "link:Keyword"
"@keyword.coroutine"     = "link:Keyword"
"@keyword.directive"     = "link:PreProc"
"@keyword.function"      = "link:Keyword"
"@keyword.import"        = "link:Include"
"@keyword.operator"      = "link:Operator"
"@label"                 = "link:Special"
"@method"                = "link:Function"
"@module"                = "link:Type"
"@namespace"             = "link:Statement"
"@number"                = "link:Constant"
"@operator"              = "link:Operator"
"@parameter"             = "yellow"
"@preproc"               = "link:PreProc"
"@property"              = "link:Identifier"
"@punctuation.bracket"   = "link:Delimiter"
"@punctuation.delimiter" = "link:Delimiter"
"@punctuation.special"   = "orange"
"@repeat"                = "link:Statement"
"@string.escape"         = "link:Special"
"@string"                = "link:String"
"@string.regexp"         = "yellow"
"@string.special"        = "link:Special"
"@tag"                   = "blue"
"@tag.attribute"         = "fg1"
"@tag.delimiter"         = "blue"
"@text"                  = "fg1"
"@text.title"            = "link:Title"
"@text.uri"              = "link:Uri"
"@text.warning"          = "link:Todo"
"@type.builtin"          = "link:Statement"
"@type.definition"       = "link:Keyword"
"@type"                  = "link:Type"
"@type.qualifier"        = "link:Keyword"
"@variable"              = "link:Identifier"
"@variable.builtin"      = "link:Statement"
"@variable.member"       = "link:Identifier"
"@variable.parameter"    = "yellow"

# Language specific highlights
"@constant.bash"                 = "fg1"
"@constructor.lua"               = "link:Delimiter"
"@keyword.directive.bash"        = "link:Comment"
"@keyword.directive.python"      = "link:Comment"
"@keyword.exception.rust"        = "link:PreProc"
"@property.json"                 = "blue"
"@property.toml"                 = "blue"
"@property.yaml"                 = "blue"
"@string.csv"                    = "fg1"
"@string.special.path.nix"       = "cyan"
"@variable.parameter.bash"       = "fg1"
"@variable.parameter.powershell" = "fg1"

# Markup highlights
"@markup.heading.1"  = "red"
"@markup.heading.2"  = "yellow"
"@markup.heading.3"  = "green"
"@markup.heading.4"  = "cyan"
"@markup.heading.5"  = "blue"
"@markup.heading.6"  = "purple"
"@markup.list"       = "green"
"@markup.link.label" = "blue - u"
"@markup.link.url"   = "cyan - u"
"@markup.raw"        = "link:ColorColumn"
"@markup.raw.block"  = "link:ColorColumn"

"@punctuation.special.markdown" = "link:Comment"

# Non treesitter highlights
csvCol0 = "fg1"
csvCol1 = "blue"
csvCol2 = "yellow"
csvCol3 = "cyan"
csvCol4 = "orange"
csvCol5 = "purple"
csvCol6 = "green"
csvCol7 = "sky"
csvCol8 = "red"

# Plugins
BlinkCmpMenu              = "fg1 bg3"
BlinkCmpKind              = "link:Special"
BlinkCmpKindClass         = "link:Type"
BlinkCmpKindColor         = "link:Special"
BlinkCmpKindConstant      = "link:Constant"
BlinkCmpKindConstructor   = "link:@constructor"
BlinkCmpKindEnum          = "link:Constant"
BlinkCmpKindEnumMember    = "link:@property"
BlinkCmpKindEvent         = "link:Special"
BlinkCmpKindField         = "fg1"
BlinkCmpKindFile          = "fg1"
BlinkCmpKindFolder        = "link:Directory"
BlinkCmpKindFunction      = "link:Function"
BlinkCmpKindInterface     = "link:Type"
BlinkCmpKindKeyword       = "link:Keyword"
BlinkCmpKindMethod        = "link:Function"
BlinkCmpKindModule        = "link:Type"
BlinkCmpKindOperator      = "link:Operator"
BlinkCmpKindProperty      = "link:@property"
BlinkCmpKindReference     = "fg1"
BlinkCmpKindSnippet       = "link:String"
BlinkCmpKindStruct        = "link:Type"
BlinkCmpKindText          = "link:String"
BlinkCmpKindTypeParameter = "link:Identifier"
BlinkCmpKindUnit          = "link:Constant"
BlinkCmpKindValue         = "fg1"
BlinkCmpKindVariable      = "fg1"
BlinkCmpDoc               = "fg1 bg3"
BlinkCmpDocBorder         = "bg3 bg3"
BlinkCmpDocSeparator      = "fg1 bg3"
BlinkCmpLabelDeprecated   = "link:Comment"

NvimTreeFolderIcon   = "link:Directory"
NvimTreeIndentMarker = "link:Directory"
NvimTreeWindowPicker = "bg0 filled_blue b"
NvimTreeRootFolder   = "purple"
NvimTreeSpecialFile  = "orange"
NvimTreeExecFile     = "green"
NvimTreeDeletedIcon  = "red"
NvimTreeGitMergeIcon = "yellow"
NvimTreeGitDirtyIcon = "red"

FzfLuaBorder       = "link:Comment"
FzfLuaBufNr        = "green"
FzfLuaFzfScrollbar = "grey"
FzfLuaHeaderBind   = "link:Special"
FzfLuaHeaderText   = "link:Title"
FzfLuaLivePrompt   = "fg1"
FzfLuaPathLineNr   = "fg1"
FzfLuaTabMarker    = "green"
FzfLuaTabTitle     = "link:Title"
FzfLuaTitle        = "fg1"

IblIndent     = "link:NonText"
IblScope      = "link:LineNr"
IblWhitespace = "link:Whitespace"

AgenticDiffAddWord              = "bg0 filled_green b"
AgenticDiffDeleteWord           = "bg0 filled_red b"
AgenticPermissionButtonAllow    = "bg0 filled_green"
AgenticPermissionButtonInactive = "bg0 filled_purple"
AgenticPermissionButtonReject   = "bg0 filled_red"
AgenticSpinnerGenerating        = "cyan - b"
AgenticSpinnerSearching         = "yellow - b"
AgenticSpinnerThinking          = "purple - b"
AgenticStatusCompleted          = "green"
AgenticStatusFailed             = "red"
AgenticStatusPending            = "purple"
AgenticTitle                    = "bg0 filled_blue b"

WhichKeyNormal = "fg1 statusline_bg"

[globals]
terminal_color_0          = "bg2"
terminal_color_1          = "red"
terminal_color_2          = "green"
terminal_color_3          = "orange"
terminal_color_4          = "blue"
terminal_color_5          = "purple"
terminal_color_6          = "cyan"
terminal_color_7          = "fg1"
terminal_color_8          = "grey"
terminal_color_9          = "red"
terminal_color_10         = "green"
terminal_color_11         = "yellow"
terminal_color_12         = "blue"
terminal_color_13         = "purple"
terminal_color_14         = "cyan"
terminal_color_15         = "fg2"
terminal_color_background = "bg0"
terminal_color_foreground = "fg1"
