name = "edge"
background = "light"

[hues]

[colors]
black       = "#dde2e7"
bg_dim      = "#e8ebf0"
bg0         = "#fafafa"
bg1         = "#eef1f4"
bg2         = "#e8ebf0"
bg3         = "#e8ebf0"
bg4         = "#dde2e7"
bg_grey     = "#bcc5cf"
bg_red      = "#e17373"
diff_red    = "#f6e4e4"
bg_green    = "#76af6f"
diff_green  = "#e5eee4"
bg_blue     = "#6996e0"
diff_blue   = "#e3eaf6"
bg_purple   = "#bf75d6"
diff_yellow = "#f0ece2"
fg          = "#4b505b"
red         = "#d05858"
yellow      = "#be7e05"
green       = "#608e32"
cyan        = "#3a8b84"
blue        = "#5079be"
purple      = "#b05ccc"
grey        = "#8790a0"
grey_dim    = "#bac3cb"

[highlights]
# Common highlight groups
Normal = "fg bg0"
NormalNC = "fg bg0"
Terminal = "fg bg0"
EndOfBuffer = "bg4 bg0"
Folded = "grey bg1"
Toolbarline = "fg bg2"
SignColumn = "fg"
FoldColumn = "grey_dim"
IncSearch = "bg0 bg_blue"
Search = "bg0 bg_green"
CurSearch = "link:IncSearch"
ColorColumn = "- bg1"
Conceal = "grey_dim"
Cursor = "- - r"
vCursor = "link:Cursor"
iCursor = "link:Cursor"
lCursor = "link:Cursor"
CursorIM = "link:Cursor"
CursorLine = "- bg1"
CursorColumn = "- bg1"
LineNr = "grey_dim"
CursorLineNr = "grey"
DiffAdd = "- diff_green"
DiffChange = "- diff_blue"
DiffDelete = "- diff_red"
DiffText = "bg0 blue"
Directory = "blue"
ErrorMsg = "red - bu"
WarningMsg = "yellow - b"
ModeMsg = "fg - b"
MoreMsg = "blue - b"
MatchParen = "- bg4"
NonText = "bg4"
Whitespace = "bg4"
SpecialKey = "bg4"
Pmenu = "fg bg2"
PmenuSbar = "- bg2"
PmenuSel = "bg0 bg_blue"
PmenuKind = "purple bg2"
PmenuExtra = "grey bg2"
WildMenu = "link:PmenuSel"
PmenuThumb = "- bg_grey"
NormalFloat = "fg bg2"
FloatBorder = "grey bg2"
Question = "yellow"
SpellBad = "- - c red"
SpellCap = "- - c yellow"
SpellLocal = "- - c blue"
SpellRare = "- - c purple"
StatusLine = "fg bg2"
StatusLineTerm = "fg bg2"
StatusLineNC = "grey bg1"
StatusLineTermNC = "grey bg1"
TabLine = "fg bg2" # diff
TabLineFill ="grey bg2" # diff
TabLineSel = "bg0 bg_blue" # diff
VertSplit = "black"
WinSeparator = "link:VertSplit"
Visual = "- bg3"
VisualNOS = "- bg3 u"
QuickFixLine = "purple - b"
Debug = "yellow"
debugPC = "bg0 bg_green"
debugBreakpoint = "bg0 bg_red"
ToolbarButton = "bg0 bg_purple"
Substitute = "bg0 yellow"
WinBarNC = "link:Grey"
DiagnosticFloatingError = "link:ErrorFloat"
DiagnosticFloatingWarn = "link:WarningFloat"
DiagnosticFloatingInfo = "link:InfoFloat"
DiagnosticFloatingHint = "link:HintFloat"
DiagnosticError = "link:ErrorText"
DiagnosticWarn = "link:WarningText"
DiagnosticInfo = "link:InfoText"
DiagnosticHint = "link:HintText"
DiagnosticVirtualTextError = "link:VirtualTextError"
DiagnosticVirtualTextWarn = "link:VirtualTextWarning"
DiagnosticVirtualTextInfo = "link:VirtualTextInfo"
DiagnosticVirtualTextHint = "link:VirtualTextHint"
DiagnosticUnderlineError = "link:ErrorText"
DiagnosticUnderlineWarn = "link:WarningText"
DiagnosticUnderlineInfo = "link:InfoText"
DiagnosticUnderlineHint = "link:HintText"
DiagnosticSignError = "link:RedSign"
DiagnosticSignWarn = "link:YellowSign"
DiagnosticSignInfo = "link:BlueSign"
DiagnosticSignHint = "link:GreenSign"
LspDiagnosticsFloatingError = "link:DiagnosticFloatingError"
LspDiagnosticsFloatingWarning = "link:DiagnosticFloatingWarn"
LspDiagnosticsFloatingInformation = "link:DiagnosticFloatingInfo"
LspDiagnosticsFloatingHint = "link:DiagnosticFloatingHint"
LspDiagnosticsDefaultError = "link:DiagnosticError"
LspDiagnosticsDefaultWarning = "link:DiagnosticWarn"
LspDiagnosticsDefaultInformation = "link:DiagnosticInfo"
LspDiagnosticsDefaultHint = "link:DiagnosticHint"
LspDiagnosticsVirtualTextError = "link:DiagnosticVirtualTextError"
LspDiagnosticsVirtualTextWarning = "link:DiagnosticVirtualTextWarn"
LspDiagnosticsVirtualTextInformation = "link:DiagnosticVirtualTextInfo"
LspDiagnosticsVirtualTextHint = "link:DiagnosticVirtualTextHint"
LspDiagnosticsUnderlineError = "link:DiagnosticUnderlineError"
LspDiagnosticsUnderlineWarning = "link:DiagnosticUnderlineWarn"
LspDiagnosticsUnderlineInformation = "link:DiagnosticUnderlineInfo"
LspDiagnosticsUnderlineHint = "link:DiagnosticUnderlineHint"
LspDiagnosticsSignError = "link:DiagnosticSignError"
LspDiagnosticsSignWarning = "link:DiagnosticSignWarn"
LspDiagnosticsSignInformation = "link:DiagnosticSignInfo"
LspDiagnosticsSignHint = "link:DiagnosticSignHint"
LspReferenceText = "link:CurrentWord"
LspReferenceRead = "link:CurrentWord"
LspReferenceWrite = "link:CurrentWord"
LspCodeLens = "link:VirtualTextInfo"
LspCodeLensSeparator = "link:VirtualTextHint"
LspSignatureActiveParameter = "link:Search"
TermCursor = "link:Cursor"
healthError = "link:Red"
healthSuccess = "link:Green"
healthWarning = "link:Yellow"

# Syntax
Type = "red"
Structure = "red"
StorageClass = "red"
Identifier = "cyan"
Constant = "yellow"
PreProc = "purple"
PreCondit = "purple"
Include = "purple"
Keyword = "purple"
Define = "purple"
Typedef = "purple"
Exception = "purple"
Conditional = "purple"
Repeat = "purple"
Statement = "purple"
Macro = "yellow"
Error = "red"
Label = "yellow"
Special = "yellow"
SpecialChar = "yellow"
Boolean = "green"
String = "green"
Character = "green"
Number = "red"
Float = "red"
Function = "blue"
Operator = "purple"
Title =" blue - b" # diff
Tag = "yellow"
Delimiter = "fg"
Todo = "bg0 blue b"
Comment = "grey"
SpecialComment = "grey"

# Predefined highlight groups
Fg = "fg"
Grey = "grey"
Red = "red"
Yellow = "yellow"
Green = "green"
Cyan = "cyan"
Blue = "blue"
Purple = "purple"
RedItalic = "red - i"
YellowItalic = "yellow - i"
GreenItalic = "green - i"
CyanItalic = "cyan - i"
BlueItalic = "blue - i"
PurpleItalic = "purple - i"
RedSign = "red"
YellowSign = "yellow"
GreenSign = "green"
CyanSign = "cyan"
BlueSign = "blue"
PurpleSign = "purple"
ErrorText = "- - c red"
WarningText = "- - c yellow"
InfoText = "- - c blue"
HintText = "- - c green"
ErrorLine = "-"
WarningLine = "-"
InfoLine = "-"
HintLine = "-"
VirtualTextWarning = "link:Grey"
VirtualTextError = "link:Grey"
VirtualTextInfo = "link:Grey"
VirtualTextHint = "link:Grey"
ErrorFloat = "red bg2"
WarningFloat = "yellow bg2"
InfoFloat = "blue bg2"
HintFloat = "green bg2"
CurrentWord = "bg0 green"

# Treesitter
"@annotation" = "link:Purple"
"@attribute" = "link:Yellow"
"@boolean" = "link:Red"
"@character" = "link:Green"
"@character.special" = "link:SpecialChar"
"@comment" = "link:Comment"
"@conceal" = "link:Grey"
"@conditional" = "link:Purple"
"@constant" = "link:Red"
"@constant.builtin" = "link:Red"
"@constant.macro" = "link:Cyan"
"@constructor" = "link:Blue"
"@debug" = "link:Debug"
"@define" = "link:Define"
"@error" = "link:Error"
"@exception" = "link:Purple"
"@field" = "link:Cyan"
"@float" = "link:Red"
"@function" = "link:Blue"
"@function.builtin" = "link:Blue"
"@function.call" = "link:Blue"
"@function.macro" = "link:Blue"
"@include" = "link:Purple"
"@keyword" = "link:Purple"
"@keyword.function" = "link:Purple"
"@keyword.operator" = "link:Purple"
"@keyword.return" = "link:Purple"
"@label" = "link:Purple"
"@math" = "link:Green"
"@method" = "link:Blue"
"@method.call" = "link:Blue"
"@namespace" = "link:Yellow"
"@none" = "link:Fg"
"@number" = "link:Red"
"@operator" = "link:Purple"
"@parameter" = "link:Fg"
"@parameter.reference" = "link:Red"
"@preproc" = "link:PreProc"
"@property" = "link:Cyan"
"@punctuation.bracket" = "link:Grey"
"@punctuation.delimiter" = "link:Grey"
"@punctuation.special" = "link:Yellow"
"@repeat" = "link:Purple"
"@storageclass" = "link:Purple"
"@storageclass.lifetime" = "link:Purple"
"@strike" = "link:Grey"
"@string" = "link:Green"
"@string.escape" = "link:Yellow"
"@string.regex" = "link:Yellow"
"@string.special" = "link:SpecialChar"
"@symbol" = "link:Red"
"@tag" = "link:Red"
"@tag.attribute" = "link:Blue"
"@tag.delimiter" = "link:Purple"
"@text" = "link:Green"
"@text.danger" = "bg0 red b"
"@text.diff.add" = "link:diffAdded"
"@text.diff.delete" = "link:diffRemoved"
"@text.emphasis" = "- - i"
"@text.environment" = "link:Macro"
"@text.environment.name" = "link:Type"
"@text.literal" = "link:String"
"@text.math" = "link:@math"
"@text.note" = "bg0 green b"
"@text.reference" = "link:Constant"
"@text.strike" = "link:Grey"
"@text.strong" = "- - b"
"@text.title" = "link:Title"
"@text.todo" = "link:Todo"
"@text.todo.checked" = "link:Green"
"@text.todo.unchecked" = "link:Ignore"
"@text.underline" = "- - u"
"@text.uri" = "link:markdownUrl"
"@text.warning" = "bg0 yellow b"
"@todo" = "link:Todo"
"@type" = "link:Yellow"
"@type.builtin" = "link:Yellow"
"@type.definition" = "link:Yellow"
"@type.qualifier" = "link:Purple"
"@uri" = "link:markdownUrl"
"@variable" = "link:Fg"
"@variable.builtin" = "link:Cyan"

"@lsp.type.class" = "link:@type"
"@lsp.type.comment" = "link:@comment"
"@lsp.type.decorator" = "link:@function"
"@lsp.type.enum" = "link:@type"
"@lsp.type.enumMember" = "link:@property"
"@lsp.type.events" = "link:@label"
"@lsp.type.function" = "link:@function"
"@lsp.type.interface" = "link:@type"
"@lsp.type.keyword" = "link:@keyword"
"@lsp.type.macro" = "link:@constant.macro"
"@lsp.type.method" = "link:@method"
"@lsp.type.modifier" = "link:@type.qualifier"
"@lsp.type.namespace" = "link:@namespace"
"@lsp.type.number" = "link:@number"
"@lsp.type.operator" = "link:@operator"
"@lsp.type.parameter" = "link:@parameter"
"@lsp.type.property" = "link:@property"
"@lsp.type.regexp" = "link:@string.regex"
"@lsp.type.string" = "link:@string"
"@lsp.type.struct" = "link:@type"
"@lsp.type.type" = "link:@type"
"@lsp.type.typeParameter" = "link:@type.definition"
"@lsp.type.variable" = "link:@variable"
"DiagnosticUnnecessary" = "link:WarningText"

# Markdown
# call edge#highlight('markdownH1', s:palette.purple, s:palette.none, 'bold')
# call edge#highlight('markdownH2', s:palette.red, s:palette.none, 'bold')
# call edge#highlight('markdownH3', s:palette.blue, s:palette.none, 'bold')
# call edge#highlight('markdownH4', s:palette.yellow, s:palette.none, 'bold')
# call edge#highlight('markdownH5', s:palette.green, s:palette.none, 'bold')
# call edge#highlight('markdownH6', s:palette.cyan, s:palette.none, 'bold')
# call edge#highlight('markdownUrl', s:palette.green, s:palette.none, 'underline')
# call edge#highlight('markdownItalic', s:palette.none, s:palette.none, 'italic')
# call edge#highlight('markdownBold', s:palette.none, s:palette.none, 'bold')
# call edge#highlight('markdownItalicDelimiter', s:palette.grey, s:palette.none, 'italic')
# highlight! link markdownCode Green
# highlight! link markdownCodeBlock Green
# highlight! link markdownCodeDelimiter Green
# highlight! link markdownBlockquote Grey
# highlight! link markdownListMarker Red
# highlight! link markdownOrdepurpleListMarker Red
# highlight! link markdownRule Yellow
# highlight! link markdownHeadingRule Grey
# highlight! link markdownUrlDelimiter Grey
# highlight! link markdownLinkDelimiter Grey
# highlight! link markdownLinkTextDelimiter Grey
# highlight! link markdownHeadingDelimiter Grey
# highlight! link markdownLinkText Purple
# highlight! link markdownUrlTitleDelimiter Blue
# highlight! link markdownIdDeclaration markdownLinkText
# highlight! link markdownBoldDelimiter Grey
# highlight! link markdownId Green
# 
# # Extended file types
# highlight! link diffAdded Green
# highlight! link diffRemoved Red
# highlight! link diffChanged Blue
# highlight! link diffOldFile Green
# highlight! link diffNewFile Cyan
# highlight! link diffFile Yellow
# highlight! link diffLine Grey
# highlight! link diffIndexLine Yellow

TelescopeBorder = "link:Grey"
TelescopeTitle = "link:Fg"
TelescopeSelection =" link:DiffChange" # diff

IndentBlanklineContextChar = "link:Grey"
IndentBlanklineChar = "link:NonText"

GitSignsAdd = "link:GreenSign"
GitSignsChange = "link:BlueSign"
GitSignsDelete = "link:RedSign"
GitSignsAddNr = "link:Green"
GitSignsChangeNr = "link:Blue"
GitSignsDeleteNr = "link:Red"
GitSignsAddLn = "link:DiffAdd"
GitSignsChangeLn = "link:DiffChange"
GitSignsDeleteLn = "link:DiffDelete"
GitSignsCurrentLineBlame = "link:Grey"
