-- This file was generated by HueVim, feel free to perform edits to suit your needs.
-- It will not be overwritten unless the `--overwrite-init` is specified

local M = {}

function M.init(theme)
    if theme then
        vim.o.background = theme
    end

    vim.cmd("hi clear")

    if vim.fn.exists("syntax_on") then
        vim.cmd("syntax reset")
    end

    vim.g.colors_name = "edge"
    vim.o.termguicolors = true

    palette = require(string.format("edge.highlights-%s", vim.o.background))
    palette.set_highlights()
    palette.set_globals()
end

return M
